name: Build & Test JDK 25

on:
  push:
    branches: [jdk25]
  workflow_dispatch:

jobs:
  code-quality:
    if: github.repository == 'beehive-lab/TornadoVM'
    runs-on: [self-hosted, Linux, x64]
    env:
      JAVA_HOME: /opt/jenkins/jdks/jdk-25.0.2
      MAVEN_HOME: /opt/maven
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        run: |
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
          ./mvnw checkstyle:check

  build-opencl:
    if: github.repository == 'beehive-lab/TornadoVM'
    runs-on: [self-hosted, Linux, x64]
    needs: code-quality
    timeout-minutes: 20
    env:
      JAVA_HOME: /opt/jenkins/jdks/jdk-25.0.2
      CMAKE_ROOT: /opt/jenkins/cmake-3.25.2-linux-x86_64
      MAVEN_HOME: /opt/maven
      GRAAL_JARS: /opt/graal25Jars/
      TORNADO_ROOT: ${{ github.workspace }}
      TORNADOVM_HOME: ${{ github.workspace }}/bin/sdk
      VENV_PATH: ${{ github.workspace }}/venv-opencl
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          echo "$MAVEN_HOME/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Setup Python venv
        run: |
          python3 -m venv $VENV_PATH
          source $VENV_PATH/bin/activate
          pip install --upgrade pip tqdm psutil

      - name: Build TornadoVM (opencl)
        run: |
          mkdir -p graalJars && cp $GRAAL_JARS/* graalJars/
          source $VENV_PATH/bin/activate
          make jdk25 BACKEND=opencl

      - name: Run opencl fast unit tests
        run: |
          source $VENV_PATH/bin/activate
          source setvars.sh
          tornado --devices
          make fast-tests

  build-ptx:
    if: github.repository == 'beehive-lab/TornadoVM'
    runs-on: [self-hosted, Linux, x64]
    needs: build-opencl
    timeout-minutes: 20
    env:
      JAVA_HOME: /opt/jenkins/jdks/jdk-25.0.2
      CMAKE_ROOT: /opt/jenkins/cmake-3.25.2-linux-x86_64
      MAVEN_HOME: /opt/maven
      GRAAL_JARS: /opt/graal25Jars/
      TORNADO_ROOT: ${{ github.workspace }}
      TORNADOVM_HOME: ${{ github.workspace }}/bin/sdk
      VENV_PATH: ${{ github.workspace }}/venv-ptx
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          echo "$MAVEN_HOME/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Setup Python venv
        run: |
          python3 -m venv $VENV_PATH
          source $VENV_PATH/bin/activate
          pip install --upgrade pip tqdm psutil

      - name: Build TornadoVM (ptx)
        run: |
          mkdir -p graalJars && cp $GRAAL_JARS/* graalJars/
          source $VENV_PATH/bin/activate
          make jdk25 BACKEND=ptx

      - name: Run ptx fast unit tests
        run: |
          source $VENV_PATH/bin/activate
          source setvars.sh
          make fast-tests

  build-spirv:
    if: github.repository == 'beehive-lab/TornadoVM'
    runs-on: [self-hosted, Linux, x64]
    needs: code-quality
    timeout-minutes: 20
    env:
      JAVA_HOME: /opt/jenkins/jdks/jdk-25.0.2
      CMAKE_ROOT: /opt/jenkins/cmake-3.25.2-linux-x86_64
      MAVEN_HOME: /opt/maven
      GRAAL_JARS: /opt/graal25Jars/
      TORNADO_ROOT: ${{ github.workspace }}
      TORNADOVM_HOME: ${{ github.workspace }}/bin/sdk
      VENV_PATH: ${{ github.workspace }}/venv-spirv
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          echo "$MAVEN_HOME/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Setup Python venv
        run: |
          python3 -m venv $VENV_PATH
          source $VENV_PATH/bin/activate
          pip install --upgrade pip tqdm psutil

      - name: Build TornadoVM (spirv)
        run: |
          mkdir -p graalJars && cp $GRAAL_JARS/* graalJars/
          source $VENV_PATH/bin/activate
          make jdk25 BACKEND=spirv

      - name: Run spirv fast unit tests
        run: |
          source $VENV_PATH/bin/activate
          source setvars.sh
          make fast-tests

  build-macOs-opencl:
    if: github.repository == 'beehive-lab/TornadoVM'
    runs-on: [self-hosted, macOS, arm64]
    needs: code-quality
    timeout-minutes: 45
    env:
      JAVA_HOME: /opt/jenkins/jdks/jdk-25/Contents/Home
      TORNADO_ROOT: ${{ github.workspace }}
      TORNADOVM_HOME: ${{ github.workspace }}/bin/sdk
      VENV_PATH: ${{ github.workspace }}/venv-opencl
      CMAKE_ROOT: /opt/homebrew/bin/cmake
      MAVEN_HOME: /opt/homebrew/bin/mvn
      GRAAL_JARS: /opt/graalJars
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          echo "$MAVEN_HOME/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Setup Python venv
        run: |
          python3 -m venv $VENV_PATH
          source $VENV_PATH/bin/activate
          pip install --upgrade pip tqdm psutil

      - name: Build TornadoVM (opencl)
        run: |
          mkdir -p graalJars && cp $GRAAL_JARS/* graalJars/
          source $VENV_PATH/bin/activate
          make jdk25 BACKEND=opencl

      - name: Run opencl fast unit tests
        run: |
          source $VENV_PATH/bin/activate
          source setvars.sh
          tornado --devices
          make fast-tests
