name: Build on [push]

on:
  push:
    branches: [feat/ci, develop, master]
    pull_request:
      branches: [ develop ]
      types: [ opened, synchronize, reopened ]
  workflow_dispatch:
env:
  JAVA_HOME: /opt/jenkins/jdks/graal-23.1.0/jdk-21.0.3
  CMAKE_ROOT: /opt/jenkins/cmake-3.25.2-linux-x86_64
  MAVEN_HOME: /opt/maven
  GRAAL_JARS: /opt/graalJars

jobs:
  code-quality:
    runs-on: self-hosted
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkstyle
        run: |
          export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
          ./mvnw checkstyle:check

  build-and-test:
    runs-on: self-hosted
    needs: code-quality
    strategy:
      fail-fast: true
      matrix:
        backend: [opencl, ptx, spirv]

    env:
      TORNADO_ROOT: ${{ github.workspace }}
      TORNADO_SDK: ${{ github.workspace }}/bin/sdk
      VENV_PATH: ${{ github.workspace }}/venv-${{ matrix.backend }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          echo "$MAVEN_HOME/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Setup Python venv
        run: |
          python3 -m venv $VENV_PATH
          source $VENV_PATH/bin/activate
          pip install --upgrade pip
          pip install tqdm psutil

      - name: Build TornadoVM (${{ matrix.backend }})
        run: |
          cd $TORNADO_ROOT
          mkdir -p graalJars && cp $GRAAL_JARS/* graalJars/
          source $VENV_PATH/bin/activate
          make jdk21 BACKEND=${{ matrix.backend }}

      - name: Run ${{ matrix.backend }} fast unit tests
        run: |
          cd $TORNADO_ROOT
          source $VENV_PATH/bin/activate
          source setvars.sh
          tornado --devices
          make fast-tests
